version: "3"

services:
  app:
    restart: always
    image: talshaham/jenkins:latest
    command: gunicorn -w 4 -b 0.0.0.0:5000 wsgi:app
  nginx:
    container_name: nginx
    restart: always
    image: talshaham/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - app
