version: "3"

services:
  app:
    build:
      context: sudo ssh -i key_pair1.pem ec2-user@ec2-16-171-27-142.eu-north-1.compute.amazonaws.com
    ports:
      - "5000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf #copty app.conf to etc nginx
    depends_on:
      - app
    ports:
      - "80:80"
