version: "3"

services:
  app:
    image: talshaham/jenkins:latest

  nginx:
    image: nginx:alpine
    volumes:
      - ./app.conf:/etc/nginx/conf.d/app.conf #copty app.conf to etc nginx
    command:
      - sudo rm /etc/nginx/conf.d/default.conf 
    depends_on:
      - app
    ports:
      - "80:80"
