version: "3"

services:
  app:
    image: talshaham/jenkins:latest

  nginx:
    image: nginx:alpine
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf #copty app.conf to etc nginx
    depends_on:
      - app
    ports:
      - "80:80"
